### ISSUE TITLE
Pas de bol: Le paiement est optionnel la avec remise en main propre...

### ISSUE THREAD

**Issue by Lavondysss** [iwazaru/biblys-theme-lavondyss#16]
... Comme si le client s'apprêtait à débouler à Scylla.

Ce serait possible de rendre le paiement obligatoire comme pour une livraison ? J'ai ptet mal fait un truc mais il m'a semblé qu'il n'y avait que des fourchettes de valeur dans les paramètres de FDP.

**Comment by iwazaru** [comment]
Ce n'est pas vraiment possible car le choix du mode de livraison doit se faire avant le paiement (puisqu'il peut influer sur le montant à payer). Et une fois que le client a validé sa commande, difficile de l'empêcher de se rendre à Scylla s'il n'a pas payé.

Mais quelques pistes :
- dans le champ "commentaire" de la tranche de frais de port, tu peux entrer un message qui apparaît lorsque le client sélectionne ce mode, et par exemple indiquer ici que la commande ne sera livrée que lorsqu'elle sera payée
- c'est toi qui déclenche l'envoi du mail informant le client que la commande est prête à être retirée, donc libre à toi de ne le faire que lorsque le client a effectivement payé (et le relancer dans le cas contraire)
- c'est un peu dommage de demander à un client d'envoyer un chèque à une adresse puis de se rendre à une autre seulement une fois que le chèque a été reçu : à voir si Xavier ne peut pas gérer une petite caisse pour toi (comme il le faisait pour Ys)

**Comment by Lavondysss** [comment]
Oui, c'est d'une logique implacable. Ce genre de chose va finir par rentrer
dans le ciboulot.
J'avais dans l'idée déjà de le suggérer dans le commentaire, je l'ai fait
du coup.
Merci pour tes réponses !

Le mar. 7 juin 2022 à 14:52, Clément Bourgoin ***@***.***> a
écrit :
