### ISSUE TITLE
Insérer dans chaque résultat des informations sur l'ouvrage style éditeur/collection/traducteur

### ISSUE THREAD

**Issue by iwazaru** [iwazaru/biblys-theme-lavondyss#4]
Avec liens hypertextes et mène à une page de résultat triée.

**Comment by Lavondysss** [comment]
bis:
_A mon avis ça fait partie des priorités, pour le moment les gens vu qu'il n'y a pas de page qui montre directement le stock vont surtout l'appréhender en passant par la recherche textuelle. Si les résultats sont plus lisibles, is mieux._ 

Profiter un maximum de l'hypertextualité pour éviter aux gens de repasser par la barre.

**Comment by iwazaru** [comment]
J'ai ajouté la collection et l'éditeur, et ajouté des liens sur les auteurs et les cycles. Je n'ai pas mis le traducteur, ça me paraissait un peu "overkill" à cet endroit. Mais n'hésite pas à rouvrir le ticket si tu n'es pas d'accord pour le traducteur (c'est toi qui décides au final) ou si tu veux voir d'autres infos à cet endroit.
