### ISSUE TITLE
Ajouter les photos des exemplaires sur la fiche article

### ISSUE THREAD

**Issue by iwazaru** [iwazaru/biblys-theme-lavondyss#8]
> Toujours sur la page d'un ouvrage, il n'apparaît pas de photo de l'exemplaire d'occasion. C'est normal ?
Je suis allé voir aussi un exemplaire donc je me souvenais avoir ajouté une remarque sur l'état, en l'occurrence [Elric des dragons](https://lavondyss.biblys.fr/a/michael-moorcock/elric-des-dragons-1206) en Aventure fantastique, concernant la jaquette et le rhodoïd mais je ne la vois pas apparaître.

**Comment by Lavondysss** [comment]
Grosse priorité également, sans ça je risque difficilement d'être pris au sérieux =/
