### ISSUE TITLE
Afficher par défaut les exemplaires en stock en premier dans les résultats de la recherche.

### ISSUE THREAD

**Issue by Lavondysss** [iwazaru/biblys-theme-lavondyss#9]
En l'état certains exemplaires en stock sont planqués derrière des pages de livres que je n'ai pas. Je ne fais pas trop confiance aux gens pour aller chercher quelque chose en page 4 ou 5 des résultats malheureusement. C'est aussi compliqué que faire un tri à postériori ou pas ? De changer le paramètre initial de recherche.

Par exemple, je viens de test avec Orson Scott Card, j'ai des trucs qui se baladent jusqu'à la page 14 des résultats :'(

-----

TODO
- [x] Filtre "Articles en stock uniquement"
- [x] Filtrer selon le stock du site courant uniquement
- [x] Gérer le nombre de résultats
- [x] Gérer la pagination
- [x] Uniquement avec l'option stock réel

**Comment by iwazaru** [comment]
C'est compliqué d'afficher en premier les articles avec un exemplaire un stock, car ça ne peut pas être un critère de tri.
Mais j'ai pu ajouter un filtre avec une case à cocher pour "Afficher uniquement les exemplaire en stock" :
https://lavondyss.fr/articles/search?q=orson+scott+card&in-stock=1
Je pense que combiné à l'option de tri par date d'ajout au stock, par exemple, on s'approchera de la demande initiale.

Je ne clos pas le ticket parce qu'il reste des problèmes à régler avec le nombre de résultats et la pagination, mais ça me paraît déjà rendre la recherche plus claire !

**Comment by Lavondysss** [comment]
C'est déjà super, ça ajoute beaucoup de clarté.
Merci beaucoup !

Oui, j'ai vu pour la pagination. Ça donne un petit côté dungeon crawler
"ah, une salle vide".

Le jeu. 9 juin 2022 à 14:06, Clément Bourgoin ***@***.***> a
écrit :
